# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a1aab9ddbe4691f16ca559a5d29c903c79023c76c648b20a27a9141efbb3f42c96da567160dff0e936ac608c71bc2516d558e2a7ef34a09c5f5c5c4bac2fbe9f

test:
  secret_key_base: 12e72e4a2c8664ec4adb040fa7ce29560937fb749ac6b1527fdd449c3779aa6d0c1c2c76e4c0e9f46e1f0d26e3de27ee5123c31cdda5d6436b8df3ceab9149e8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
